# Generated by Django 2.0.6 on 2018-06-25 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inchiCoreLayers', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Isotope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isotopeLayer', models.CharField(max_length=200)),
                ('beta_fact', models.FloatField()),
                ('inchiCoreLayers', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='search.ChemSpecies')),
            ],
        ),
        migrations.CreateModel(
            name='Smiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(max_length=200)),
                ('inchiCoreLayers', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='search.ChemSpecies')),
            ],
        ),
    ]
